---
title: "binary"
author: "Sith J"
date: "September 9, 2015"
output: html_document
---

This is the script for explore the method for constructing networks from binary data

```{r load library}
library(ggplot2)
require(dplyr)
require(reshape)
require(reshape2)
require(qgraph)
library(gridExtra)
library(cowplot)
library(lubridate)
library(XLConnect)
library(qgraph)
library(IsingFit)
library(doBy)
library(cluster)
```

You can also embed plots, for example:

```{r load data}
Filepath <- "E:/Google Drive/1.SKEP1/SKEP1survey.xls" # please check your file in shared google drive
Filepath <- "~/Google Drive/1.SKEP1/SKEP1survey.xls"
data <- readWorksheetFromFile(Filepath, sheet = 1)
```

```{r clean data}
#### clean define the missing value ####
data[data == "-"] <- NA # replace '-' with NA
data[data == ""] <- NA # replace 'missing data' with NA
#### end cleaning of data ####
```

```{r rename names of variables}
#### to lower variable names ####
names(data) <- tolower(names(data))
#### end setting the varibales ####
```

```{r correct the type of variables}
data <- transform(data, 
                  phase = as.factor(phase),
                  fno = as.character(fno),
                  identifier = as.character(identifier),
                  country = as.factor(country),
                  year = as.factor(year),
                  season  = as.factor(season),   
                  lat = as.numeric(lat),
                  long = as.numeric(long),      
                  village = as.character(village), 
                  fa = as.numeric(fa),
                  fn = as.character(fn),
                  lfm = as.character(lfm),
                  pc = as.factor(pc),
                  fp = as.character(fp),        
                  cem = as.factor(cem),     
                  ast = as.factor(ast),       
                  nplsqm = as.numeric(nplsqm),
                  ced = dmy(ced),# Date data try to use as.Data(., format = '%d-%b-%y') it is not working
                  cedjul = as.numeric(cedjul),
                  hd = dmy(hd), 
                  hdjul = as.numeric(hdjul),     
                  ccd = as.numeric(ccd),
                  cvr = as.character(cvr),
                  vartype = as.factor(vartype),
                  varcoded = as.factor(varcoded),
                  fym = as.character(fym),
                  fymcoded = as.factor(fymcoded),
                  n = as.numeric(n),
                  p = as.numeric(p) ,
                  k = as.numeric(k),
                  mf = as.numeric(mf),        
                  wcp = as.factor(wcp),      
                  mu = as.character(mu) ,     
                  iu = as.numeric(iu),     
                  hu = as.numeric(hu),      
                  fu = as.numeric(fu),      
                  cs  = as.factor(cs),      
                  ldg  =  as.numeric(ldg),  
                  yield = as.numeric(yield) ,
                  dscum = as.factor(dscum),   
                  wecum = as.factor(wecum),   
                  ntmax = as.numeric(ntmax), 
                  npmax = as.numeric(npmax),    
                  nltmax = as.numeric(nltmax),  
                  nlhmax = as.numeric(nltmax),  
                  waa = as.numeric(waa),      
                  wba = as.numeric(wba) ,   
                  dhx =  as.numeric(dhx),  
                  whx =  as.numeric(whx),     
                  ssx  = as.numeric(ssx),  
                  wma = as.numeric(wma), 
                  lfa = as.numeric(lfa),
                  lma = as.numeric(lma),   
                  rha  = as.numeric(rha) ,
                  thrx = as.numeric(thrx),    
                  pmx = as.numeric(pmx),    
                  defa  = as.numeric(defa) ,
                  bphx = as.numeric(bphx),   
                  wbpx = as.numeric(wbpx),    
                  awx  = as.numeric(awx), 
                  rbx =as.numeric(rbx),   
                  rbbx = as.numeric(rbbx),  
                  glhx  = as.numeric(glhx), 
                  stbx=as.numeric(stbx),    
                  rbpx = as.numeric(rbpx), 
                  hbx= as.numeric(hbx),
                  bbx = as.numeric(bbx),    
                  blba = as.numeric(blba),    
                  lba = as.numeric(lba),    
                  bsa = as.numeric(bsa),    
                  blsa = as.numeric(blsa),  
                  nbsa = as.numeric(nbsa),  
                  rsa  = as.numeric(rsa),   
                  lsa = as.numeric(lsa),    
                  shbx = as.numeric(shbx) ,  
                  shrx = as.numeric(shrx),    
                  srx= as.numeric(srx),    
                  fsmx = as.numeric(fsmx),   
                  nbx =  as.numeric(nbx),   
                  dpx = as.numeric(dpx),    
                  rtdx  = as.numeric(rtdx),  
                  rsdx  = as.numeric(rsdx),
                  gsdx  =as.numeric(gsdx),   
                  rtx = as.numeric(rtx)
) 
```

```{r select out the variable}
#### Delete the unnessary variables variables without data (NA) ####
data$phase <- NULL # there is only one type yype of phase in the survey
data$identifier <- NULL # this variable is not included in the analysis
data$village <- NULL
data$fa <- NULL # field area is not include in the analysis
data$fn <- NULL # farmer name can not be included in this survey analysis
data$fp <- NULL # I do not know what is fp
data$lfm <- NULL # there is only one type of land form in this survey
data$ced <- NULL # Date data can not be included in the network analysis
data$cedjul <- NULL
data$hd <- NULL # Date data can not be included in the network analysis
data$hdjul <- NULL
data$cvr <- NULL
data$varcoded <- NULL # I will recode them 
data$fym.coded <- NULL
data$mu <- NULL # no record
data$nplsqm <- NULL
#### Delete the unnessary variables variables without data (NA) ####
```


```{r}
#### Recoding the factor ####
# Previous crop
data$pc <- ifelse(data$pc == "rice", 1, 0)
#### end of recoding the factor ####
```

```{r}
# fym there are two type 0 and 1, raw data are recorded as no, yes, and value, if the value is 0 which mean 0 and if the value more than 0 which means 1 

data$fym <- ifelse(data$fym == "no", 0, 
                  ifelse(data$fym == "0", 0, 1
                         )
                  )
```

```{r}
# vartype there are three type treditional varieties, modern varities and hybrid
data$vartype <- ifelse(data$vartype == "tv", 1,
                       ifelse(data$vartype == "mv", 2,
                              ifelse(data$vartype == "hyb", 3, NA
                                     )
                              )
                       )
```


```{r}
#Crop establisment method
levels(data$cem)[levels(data$cem) == "trp"] <- 1
levels(data$cem)[levels(data$cem) == "TPR"] <- 1
levels(data$cem)[levels(data$cem) == "DSR"] <- 2
levels(data$cem)[levels(data$cem) == "dsr"] <- 2
```


```{r}
# wcp weed control management
levels(data$wcp)[levels(data$wcp) == "hand"] <- 1
levels(data$wcp)[levels(data$wcp) == "herb"] <- 2
levels(data$wcp)[levels(data$wcp) == "herb-hand"] <- 3
```


```{r}
# Crop Status
levels(data$cs)[levels(data$cs) == "very poor"] <- 1
levels(data$cs)[levels(data$cs) == "poor"] <- 2
levels(data$cs)[levels(data$cs) == "average"] <- 3
levels(data$cs)[levels(data$cs) == "good"] <- 4
levels(data$cs)[levels(data$cs) == "very good"] <- 5
```

```{r}
OutputProfile <- data %>% 
        select (
                country, 
                season,
                pc,
                cem,    
                vartype,
                n,
                p,
                k,
                mf,        
                wcp,      
                iu,     
                hu,      
                fu,   
                dhx,  
                whx,     
                ssx,  
                wma, 
                lfa,
                lma,   
                rha, 
                thrx,    
                pmx,    
                defa,
                bphx,   
                wbpx,
                awx, 
                rbx,   
                rbbx,  
                glhx, 
                stbx,
                hbx,  
                bbx,    
                blba,    
                lba,    
                bsa,    
                blsa,  
                nbsa,  
                rsa,   
                lsa,    
                shbx,  
                shrx,    
                srx,    
                fsmx,   
                nbx,   
                dpx,    
                rtdx,  
                rsdx,
                gsdx,   
                rtx 
        ) 

data <- OutputProfile
```

```{r}
tha <- data %>% 
        filter(country == "THA") %>%
        select(-country)
```


```{r}
temp  <- tha
start.PS <- "pc"
end.PS <- "fu"
start.col.PS <- match(start.PS, names(temp))
end.col.PS <- match(end.PS, names(temp))

PS.data <- tha[start.col.PS:end.col.PS]

PS.data <- apply(PS.data, 2, as.numeric)

mydata <- PS.data

# Prepare Data
mydata <- na.omit(mydata) # listwise deletion of missing
#mydata <- scale(mydata) # standardize variables

wss <- (nrow(mydata)-1)*sum(apply(mydata,2,var))
for (i in 2:15) wss[i] <- sum(kmeans(mydata, 
  	centers=i)$withinss)
plot(1:15, wss, type="b", xlab="Number of Clusters",
  ylab="Within groups sum of squares")


#distance matrix
dist.PS <- daisy(PS.data)

cluster.PS <- hclust(dist.PS, method = "average")
dendro.PS <- as.dendrogram(cluster.PS)
plot(dendro.PS, center = T, nodePar = list(lab.cex = 0.6,
                                           lab.col = "black", pch = NA),
     main = "Dendrogram for Production situation")

# draw retangles
rect.hclust(tree = cluster.PS, k=4, border = c("red", "blue", "green", "purple"))

#number of members in each cluster
clusterno.PS <- cutree(cluster.PS, k = 4)
# cophenitic correlation
rcluster.PS <- cophenetic(cluster.PS)
cor(dist.PS, rcluster.PS)

tha <- cbind(tha, clusterno.PS)
# now we can have two grops of PS 
```

```{r}
# filter clusterno.PS == 1

temp2  <- tha %>%
        filter(clusterno.PS == 2)
start.IP <- "dhx"
end.IP <- "rtx"
start.col.IP <- match(start.IP, names(temp2))
end.col.IP <- match(end.IP, names(temp2))
temp2 <- temp2[start.col.IP:end.col.IP]
```

```{r}
temp.spearman <- cor(temp2, method = "spearman", use = "pairwise")
diag(temp.spearman) <- 0

qgraph(temp.spearman, 
        layout = "spring", 
        threshold = 0.20,
        maximum = 1,
        vsize = 5, 
        line = 3,
        posCol = "forestgreen",
        negCol = "firebrick3",
        borders = FALSE,
       # legend = TRUE,
        vTrans = 200,
        #nodeNames = Names,
        legend.cex = 0.3,
        title = "Spearman's correlation"
        )
```


```{r eval = F}
IP.var <- names(temp2)
no.IP <- length(IP.var)

for(i in 1:no.IP){
       temp3 <- ifelse(temp2[IP.var[i]] == 0, 0, 1)
        temp2[no.IP + i] <-  temp3
        colnames(temp2)[no.IP + i] <- paste("bi", IP.var[i], sep = ".")
}
IP.binary <- temp2 %>%
        select(-(1:no.IP))

#describe(IP.binary)
#clean.IP <- IP.binary %>% select(-c(bi.lma, bi.rha, bi.thrx, bi.pmx, bi.defa, bi.wbpx, bi.awx, bi.rbx, bi.rbbx, bi.stbx, bi.hbx, bi.bbx, bi.dpx, bi.rtdx, bi.rsdx, bi.gsdx))

d <- vegdist(IP.binary, method = "jaccard")
m <- as.data.frame(as.matrix((d)))
    
```

```{r evel = F}
corbi <- cor_auto(IP.binary)
IP.binary.cut <- IP.binary[,apply(IP.binary, 2, var, na.rm = TRUE) != 0] # exclude the column with variation = 0
#IP.binary <- as.matrix(as.data.frame(IP.binary))
IsingFit(IP.binary.cut, family='binomial', plot=T)

IsingFit(clean.IP, family='binomial', plot=T)

#doub.IP.binary.cut <- rbind(IP.binary.cut, IP.binary.cut)
#IsingFit(doub.IP.binary.cut, family='binomial', plot=T)
```


```{r eval=F}
phimat<-function(x) { 
 xcol<-dim(x)[2] 
 newx <- matrix(NA, nrow = xcol, ncol= xcol) 
 for(i in 1:xcol) { 
  for(j in 1:xcol) 
          newx[i,j] <- phi(table(x[,i], x[,j])) 
 } 
 
 rownames(newx) <- colnames(newx) <- colnames(x) 
 return(newx) 
} 
phimat(IP.binary)
cor(IP.binary)
```

